### ISSUE TITLE
Transparent background 

### ISSUE THREAD

**Issue by bknill** [spite/THREE.CubemapToEquirectangular#4]
Hi, 
Great plugin, works well. 

I do have an issue, I'm trying to create a transparent background for use in video processing. I've got round this by using a green sphere and using a colorkey in FFPMEG, but it's not quite right. Is there anyway to have a transparent background? 

I've got nothing in the scene apart from an object3D floating in space. 

The renderer is configured 
		renderer = new THREE.WebGLRenderer({antialias: true, preserveDrawingBuffer: true,alpha: true });
	renderer.setClearColor( 0x00ff00, 0 );

**Comment by spite** [comment]
Actually, it's funny because it's an oversight on the shader. 
I assumed the image is solid, so the opacity is not copied.

Can you try this? In the .js file, there's a line that goes like
`gl_FragColor = vec4( textureCube( map, dir ).rgb, 1. );`

Try changing it to
`gl_FragColor = textureCube( map, dir );`

and let me know if the exported image has alpha channel.

**Comment by bknill** [comment]
Thanks for getting back to me, I tried that and It throws these errors and crashes WebGL
```
THREE.WebGLShader: Shader couldn't compile.
ee @ three.min.js.jsf?ln=js:58
af @ three.min.js.jsf?ln=js:73
acquireProgram @ three.min.js.jsf?ln=js:83
v @ three.min.js.jsf?ln=js:134
renderBufferDirect @ three.min.js.jsf?ln=js:162
r @ three.min.js.jsf?ln=js:131
render @ three.min.js.jsf?ln=js:175
CubemapToEquirectangular.convert @ CubemapToEquirectangular.js.jsf?ln=js:144
(anonymous) @ SceneAdmin.js.jsf?ln=js:1270
setTimeout (async)
updateVideoImage @ SceneAdmin.js.jsf?ln=js:1268
onclick @ edit:1
three.min.js.jsf?ln=js:74 THREE.WebGLProgram: shader error:  0 gl.VALIDATE_STATUS false gl.getProgramInfoLog   
af @ three.min.js.jsf?ln=js:74
acquireProgram @ three.min.js.jsf?ln=js:83
v @ three.min.js.jsf?ln=js:134
renderBufferDirect @ three.min.js.jsf?ln=js:162
r @ three.min.js.jsf?ln=js:131
render @ three.min.js.jsf?ln=js:175
CubemapToEquirectangular.convert @ CubemapToEquirectangular.js.jsf?ln=js:144
(anonymous) @ SceneAdmin.js.jsf?ln=js:1270
setTimeout (async)
updateVideoImage @ SceneAdmin.js.jsf?ln=js:1268
onclick @ edit:1
three.min.js.jsf?ln=js:137 WebGL: INVALID_OPERATION: useProgram: program not valid
v @ three.min.js.jsf?ln=js:137
renderBufferDirect @ three.min.js.jsf?ln=js:162
r @ three.min.js.jsf?ln=js:131
render @ three.min.js.jsf?ln=js:175
CubemapToEquirectangular.convert @ CubemapToEquirectangular.js.jsf?ln=js:144
(anonymous) @ SceneAdmin.js.jsf?ln=js:1270
setTimeout (async)
updateVideoImage @ SceneAdmin.js.jsf?ln=js:1268
onclick @ edit:1
three.min.js.jsf?ln=js:181 THREE.WebGLRenderer.readRenderTargetPixels: readPixels from renderTarget failed. Framebuffer not complete.
```

Actually that error was probably caused by something else, it seems to have gone now. However the background is just black, with no transparency.

**Comment by spite** [comment]
You've probably typed or copied the code wrong, because the error says the program is not valid. 

I've just tried it and it works, but it needs a modification in three.js. If you need it to work, get three.js (not the minified version), look for the function `CubeCamera` and change the line
`var options = { format: RGBFormat, magFilter: LinearFilter, minFilter: LinearFilter };`
with
`var options = { format: RGBAFormat, magFilter: LinearFilter, minFilter: LinearFilter };`

and keep the line `gl_FragColor = textureCube( map, dir );` in the shader. 

I've tried and it works:
![pano-cubemaptoequirectangular - unmanaged-1502498928866](https://user-images.githubusercontent.com/731885/29236311-40d97004-7f09-11e7-8525-ab2d91e1e972.png)

**Comment by bknill** [comment]
Ha wow OK thanks will have a go.

**Comment by spite** [comment]
Actually, I think you can work around it without changing threejs.

You'll have to use the unmanaged example, and when creating CubeCamera, do:

```
cubeCamera = new THREE.CubeCamera( .1, 1000, 2048 );

var options = { format: THREE.RGBAFormat, magFilter: THREE.LinearFilter, minFilter: THREE.LinearFilter };
cubeCamera.renderTarget = new THREE.WebGLRenderTargetCube( 2048, 2048, options );
```

change for your values and it should work.

**Comment by bknill** [comment]
Works perfectly - you're a star!
